using System;

namespace Test
{
    public class ArgumentExceptionConstructorArgument
    {
        void _ArgumentException(int one)
        {
            throw new ArgumentException();

            throw new ArgumentException(|"one"|(0));
            throw new ArgumentException(|nameof(one)|(1));
            throw new ArgumentException("some message");

            var innerException = null as Exception;
            throw new ArgumentException(|"one"|(2), innerException);
            throw new ArgumentException(|nameof(one)|(3), innerException);
            throw new ArgumentException("some message", innerException);

            throw new ArgumentException(|"one"|(4), "some message");
            throw new ArgumentException(|nameof(one)|(5), "some message");
            throw new ArgumentException("some message", "one");
            throw new ArgumentException("some message", nameof(one));

            throw new ArgumentException(|"one"|(6), "some message", innerException);
            throw new ArgumentException(|nameof(one)|(7), "some message", innerException);
            throw new ArgumentException("some message", "one", innerException);
            throw new ArgumentException("some message", nameof(one), innerException);
        }

        void _ArgumentNullException(int one)
        {
            throw new ArgumentNullException();

            throw new ArgumentNullException("one");
            throw new ArgumentNullException(nameof(one));

            var innerException = null as Exception;
            throw new ArgumentNullException(|"one"|(8), innerException);
            throw new ArgumentNullException(|nameof(one)|(9), innerException);
            throw new ArgumentNullException("some message", innerException);

            throw new ArgumentNullException("one", "some message");
            throw new ArgumentNullException(nameof(one), "some message");
            throw new ArgumentNullException("some message", |"one"|(10));
            throw new ArgumentNullException("some message", |nameof(one)|(11));
        }

        void _ArgumentOutOfRangeException(int one)
        {
            throw new ArgumentOutOfRangeException();

            throw new ArgumentOutOfRangeException("one");
            throw new ArgumentOutOfRangeException(nameof(one));

            var innerException = null as Exception;
            throw new ArgumentOutOfRangeException(|"one"|(12), innerException);
            throw new ArgumentOutOfRangeException(|nameof(one)|(13), innerException);
            throw new ArgumentOutOfRangeException("some message", innerException);

            throw new ArgumentOutOfRangeException("one", "some message");
            throw new ArgumentOutOfRangeException(nameof(one), "some message");
            throw new ArgumentOutOfRangeException("some message", |"one"|(14));
            throw new ArgumentOutOfRangeException("some message", |nameof(one)|(15));

            throw new ArgumentOutOfRangeException("one", one, "some message");
            throw new ArgumentOutOfRangeException(nameof(one), one, "some message");
            throw new ArgumentOutOfRangeException("some message", one, |"one"|(16));
            throw new ArgumentOutOfRangeException("some message", one, |nameof(one)|(17));
        }
    }
}
---------------------------------------------------------
(0): ReSharper Warning: Parameter name used for the exception message.
(1): ReSharper Warning: Parameter name used for the exception message.
(2): ReSharper Warning: Parameter name used for the exception message.
(3): ReSharper Warning: Parameter name used for the exception message.
(4): ReSharper Warning: Parameter name used for the exception message.
(5): ReSharper Warning: Parameter name used for the exception message.
(6): ReSharper Warning: Parameter name used for the exception message.
(7): ReSharper Warning: Parameter name used for the exception message.
(8): ReSharper Warning: Parameter name used for the exception message.
(9): ReSharper Warning: Parameter name used for the exception message.
(10): ReSharper Warning: Parameter name used for the exception message.
(11): ReSharper Warning: Parameter name used for the exception message.
(12): ReSharper Warning: Parameter name used for the exception message.
(13): ReSharper Warning: Parameter name used for the exception message.
(14): ReSharper Warning: Parameter name used for the exception message.
(15): ReSharper Warning: Parameter name used for the exception message.
(16): ReSharper Warning: Parameter name used for the exception message.
(17): ReSharper Warning: Parameter name used for the exception message.
