using System;

namespace Test
{
    internal class UncatchableException
    {
        void Method()
        {
            try { }
            catch (|NullReferenceException|(0)) { }

            try { }
            catch (|NullReferenceException|(1) e) when (e.Message != null) { }
        }
    }
}
---------------------------------------------------------
(0): ReSharper Warning: The exception indicates a bug that can be avoided.
(1): ReSharper Warning: The exception indicates a bug that can be avoided.
